### PR TITLE
Card class

### PR DESCRIPTION
**Pull request by gustavoSo3**
I deviated a bit from the diagram and removed the match() function, since I ended up using dataClass wich handdles all the \_\_eq\_\_ function stuff.

Only the color and the value are used in the constructor since the image src can be generated from that information so in the \_\_post_init\_\_ we generate it usign the values.

Also apply some PEP8.

### CODE REVIEW

**Review by BamCurti — APPROVED** [review]
Looks fine tho

**Comment by BamCurti** [comment]
Match method of card has the intention of compare if the receiving card is the same color OR the same value, so it will be necessary regardless the dataclass.

**Review by BamCurti — CHANGES_REQUESTED** [review]
Match method of card has the intention of compare if the receiving card is the same color OR the same value, so it will be necessary regardless the dataclass.

**Comment by gustavoSo3** [comment]
Oh ok I made a mistake while reading the docs. Here it its

**Review by BamCurti — APPROVED** [review]
Looks good, approved

**Pull request merged**
